language: objective-c
osx_image: xcode10
before_install:
  - gem install xcpretty -N
script:
  - set -o pipefail
  - xcodebuild -project HarmonyKit.xcodeproj -scheme "HarmonyKit" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X,OS=latest" ONLY_ACTIVE_ARCH=NO test | xcpretty -c
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
