language: objective-c
osx_image: xcode12.5
before_install:
  - gem install xcpretty -N
script:
  - set -o pipefail
  - xcodebuild -project HarmonyKit.xcodeproj -scheme "HarmonyKit" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X,OS=latest" ONLY_ACTIVE_ARCH=NO test | xcpretty -c
